This code was used to obtain the LaTeX code for the table in the reports.

In [1]:
import re
import pandas as pd

## CP

In [2]:
txtfile = '../CP/out/log.txt'
with open(txtfile, 'r') as f:
    lines = [l.rstrip() for l in f.readlines()]
r1 = re.compile(r".* (Final|optimal) solution .*")
r2 = re.compile(r"Solving problem *")
nonoptimal_reg = re.compile(r"Couldn't")
time_reg = re.compile(r"\d*\b\.\d*\b")
solutions_times = [(float(time_reg.search(l).group(0)), 
                    False if nonoptimal_reg.match(l) else True) 
                   for l in list(filter(r1.match, lines))]
instances = [int(l.split('ins-')[1].split('.txt')[0]) 
             for l in list(filter(r2.match, lines))]

instance_times = {instances[i]: solutions_times[i] for i in range(len(instances))}
instance_times

{1: (0.304, True),
 10: (0.682001, True),
 11: (44.331056, True),
 12: (0.846, True),
 13: (0.944998, True),
 14: (0.854, True),
 15: (0.846001, True),
 16: (300.502358, False),
 17: (2.825997, True),
 18: (0.8970009999999999, True),
 19: (6.579, True),
 2: (0.548999, True),
 20: (8.870002, True),
 21: (4.116002, True),
 22: (16.018496, True),
 23: (1.078998, True),
 24: (2.326, True),
 25: (300.385634, False),
 26: (21.494001, True),
 27: (50.65557, True),
 28: (0.865003, True),
 29: (61.592192, True),
 3: (0.5489999999999999, True),
 30: (300.381514, False),
 31: (1.8949989999999999, True),
 32: (300.401037, False),
 33: (17.066003, True),
 34: (2.316002, True),
 35: (300.398357, False),
 36: (2.4769959999999998, True),
 37: (300.397903, False),
 38: (300.466459, False),
 39: (300.47186, False),
 4: (0.627, True),
 40: (300.549044, False),
 5: (0.6559999999999999, True),
 6: (0.560999, True),
 7: (0.563997, True),
 8: (0.5879989999999999, True),
 9: (0.591, True)}

In [3]:
results = pd.DataFrame(instance_times, index=['Solving Time', 'Solved']).T
results.sort_index()

   Solving Time Solved
1         0.304   True
2      0.548999   True
3         0.549   True
4         0.627   True
5         0.656   True
6      0.560999   True
7      0.563997   True
8      0.587999   True
9         0.591   True
10     0.682001   True
11    44.331056   True
12        0.846   True
13     0.944998   True
14        0.854   True
15     0.846001   True
16   300.502358  False
17     2.825997   True
18     0.897001   True
19        6.579   True
20     8.870002   True
21     4.116002   True
22    16.018496   True
23     1.078998   True
24        2.326   True
25   300.385634  False
26    21.494001   True
27     50.65557   True
28     0.865003   True
29    61.592192   True
30   300.381514  False
31     1.894999   True
32   300.401037  False
33    17.066003   True
34     2.316002   True
35   300.398357  False
36     2.476996   True
37   300.397903  False
38   300.466459  False
39    300.47186  False
40   300.549044  False

In [4]:
print(results.to_latex())

\begin{tabular}{lll}
\toprule
{} & Solving Time & Solved \\
\midrule
1  &        0.304 &   True \\
10 &     0.682001 &   True \\
11 &    44.331056 &   True \\
12 &        0.846 &   True \\
13 &     0.944998 &   True \\
14 &        0.854 &   True \\
15 &     0.846001 &   True \\
16 &   300.502358 &  False \\
17 &     2.825997 &   True \\
18 &     0.897001 &   True \\
19 &        6.579 &   True \\
2  &     0.548999 &   True \\
20 &     8.870002 &   True \\
21 &     4.116002 &   True \\
22 &    16.018496 &   True \\
23 &     1.078998 &   True \\
24 &        2.326 &   True \\
25 &   300.385634 &  False \\
26 &    21.494001 &   True \\
27 &     50.65557 &   True \\
28 &     0.865003 &   True \\
29 &    61.592192 &   True \\
3  &        0.549 &   True \\
30 &   300.381514 &  False \\
31 &     1.894999 &   True \\
32 &   300.401037 &  False \\
33 &    17.066003 &   True \\
34 &     2.316002 &   True \\
35 &   300.398357 &  False \\
36 &     2.476996 &   True \\
37 &   300.397903 &  False \\
38 &   300.466459 &  False \\
39 &    300.47186 &  False \\
4  &        0.627 &   True \\
40 &   300.549044 &  False \\
5  &        0.656 &   True \\
6  &     0.560999 &   True \\
7  &     0.563997 &   True \\
8  &     0.587999 &   True \\
9  &        0.591 &   True \\
\bottomrule
\end{tabular}

C:\Users\Volpe\AppData\Local\Temp/ipykernel_17912/3863709051.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(results.to_latex())

Repeat for rotated

In [5]:
txtfile = '../CP/out/log-rot.txt'
with open(txtfile, 'r') as f:
    lines = [l.rstrip() for l in f.readlines()]

solutions_times = [(float(time_reg.search(l).group(0)), 
                    False if nonoptimal_reg.match(l) else True) 
                   for l in list(filter(r1.match, lines))]
instances = [int(l.split('ins-')[1].split('.txt')[0]) 
             for l in list(filter(r2.match, lines))]

instance_times = {instances[i]: solutions_times[i] for i in range(len(instances))}
instance_times

{1: (0.348999, True),
 10: (0.9960019999999999, True),
 11: (16.865054, True),
 12: (12.361999, True),
 13: (1.704, True),
 14: (14.830001, True),
 15: (4.856, True),
 16: (55.874553, True),
 17: (43.170001, True),
 18: (300.429369, False),
 19: (300.401615, False),
 2: (0.580518, True),
 20: (300.386636, False),
 21: (300.39405, False),
 22: (300.401412, False),
 23: (300.399905, False),
 24: (27.119998, True),
 25: (300.492328, False),
 26: (301.017934, False),
 27: (300.469099, False),
 28: (300.482589, False),
 29: (300.5986, False),
 3: (1.148632, True),
 30: (300.394078, False),
 31: (300.853781, False),
 32: (300.61106, False),
 33: (301.025009, False),
 34: (300.875082, False),
 35: (13.025189, True),
 36: (126.130439, True),
 37: (300.402319, False),
 38: (300.404677, False),
 39: (300.414776, False),
 4: (0.540001, True),
 40: (300.56892, False),
 5: (0.6320009999999999, True),
 6: (0.5509999999999999, True),
 7: (0.5539999999999999, True),
 8: (0.559999, True),
 9: (0.695, True)}

In [6]:
results_rot = pd.DataFrame(instance_times, index=['Solving Time', 'Solved']).T
results_rot.sort_index()

   Solving Time Solved
1      0.348999   True
2      0.580518   True
3      1.148632   True
4      0.540001   True
5      0.632001   True
6         0.551   True
7         0.554   True
8      0.559999   True
9         0.695   True
10     0.996002   True
11    16.865054   True
12    12.361999   True
13        1.704   True
14    14.830001   True
15        4.856   True
16    55.874553   True
17    43.170001   True
18   300.429369  False
19   300.401615  False
20   300.386636  False
21    300.39405  False
22   300.401412  False
23   300.399905  False
24    27.119998   True
25   300.492328  False
26   301.017934  False
27   300.469099  False
28   300.482589  False
29     300.5986  False
30   300.394078  False
31   300.853781  False
32    300.61106  False
33   301.025009  False
34   300.875082  False
35    13.025189   True
36   126.130439   True
37   300.402319  False
38   300.404677  False
39   300.414776  False
40    300.56892  False

Join

In [7]:
joined_table = results.join(results_rot, rsuffix=' (rotated)').sort_index()
joined_table

   Solving Time Solved Solving Time (rotated) Solved (rotated)
1         0.304   True               0.348999             True
2      0.548999   True               0.580518             True
3         0.549   True               1.148632             True
4         0.627   True               0.540001             True
5         0.656   True               0.632001             True
6      0.560999   True                  0.551             True
7      0.563997   True                  0.554             True
8      0.587999   True               0.559999             True
9         0.591   True                  0.695             True
10     0.682001   True               0.996002             True
11    44.331056   True              16.865054             True
12        0.846   True              12.361999             True
13     0.944998   True                  1.704             True
14        0.854   True              14.830001             True
15     0.846001   True                  4.856             True
16   300.502358  False              55.874553             True
17     2.825997   True              43.170001             True
18     0.897001   True             300.429369            False
19        6.579   True             300.401615            False
20     8.870002   True             300.386636            False
21     4.116002   True              300.39405            False
22    16.018496   True             300.401412            False
23     1.078998   True             300.399905            False
24        2.326   True              27.119998             True
25   300.385634  False             300.492328            False
26    21.494001   True             301.017934            False
27     50.65557   True             300.469099            False
28     0.865003   True             300.482589            False
29    61.592192   True               300.5986            False
30   300.381514  False             300.394078            False
31     1.894999   True             300.853781            False
32   300.401037  False              300.61106            False
33    17.066003   True             301.025009            False
34     2.316002   True             300.875082            False
35   300.398357  False              13.025189             True
36     2.476996   True             126.130439             True
37   300.397903  False             300.402319            False
38   300.466459  False             300.404677            False
39    300.47186  False             300.414776            False
40   300.549044  False              300.56892            False

In [8]:
print(joined_table.to_latex())

\begin{tabular}{lllll}
\toprule
{} & Solving Time & Solved & Solving Time (rotated) & Solved (rotated) \\
\midrule
1  &        0.304 &   True &               0.348999 &             True \\
2  &     0.548999 &   True &               0.580518 &             True \\
3  &        0.549 &   True &               1.148632 &             True \\
4  &        0.627 &   True &               0.540001 &             True \\
5  &        0.656 &   True &               0.632001 &             True \\
6  &     0.560999 &   True &                  0.551 &             True \\
7  &     0.563997 &   True &                  0.554 &             True \\
8  &     0.587999 &   True &               0.559999 &             True \\
9  &        0.591 &   True &                  0.695 &             True \\
10 &     0.682001 &   True &               0.996002 &             True \\
11 &    44.331056 &   True &              16.865054 &             True \\
12 &        0.846 &   True &              12.361999 &             True \\
13 &     0.944998 &   True &                  1.704 &             True \\
14 &        0.854 &   True &              14.830001 &             True \\
15 &     0.846001 &   True &                  4.856 &             True \\
16 &   300.502358 &  False &              55.874553 &             True \\
17 &     2.825997 &   True &              43.170001 &             True \\
18 &     0.897001 &   True &             300.429369 &            False \\
19 &        6.579 &   True &             300.401615 &            False \\
20 &     8.870002 &   True &             300.386636 &            False \\
21 &     4.116002 &   True &              300.39405 &            False \\
22 &    16.018496 &   True &             300.401412 &            False \\
23 &     1.078998 &   True &             300.399905 &            False \\
24 &        2.326 &   True &              27.119998 &             True \\
25 &   300.385634 &  False &             300.492328 &            False \\
26 &    21.494001 &   True &             301.017934 &            False \\
27 &     50.65557 &   True &             300.469099 &            False \\
28 &     0.865003 &   True &             300.482589 &            False \\
29 &    61.592192 &   True &               300.5986 &            False \\
30 &   300.381514 &  False &             300.394078 &            False \\
31 &     1.894999 &   True &             300.853781 &            False \\
32 &   300.401037 &  False &              300.61106 &            False \\
33 &    17.066003 &   True &             301.025009 &            False \\
34 &     2.316002 &   True &             300.875082 &            False \\
35 &   300.398357 &  False &              13.025189 &             True \\
36 &     2.476996 &   True &             126.130439 &             True \\
37 &   300.397903 &  False &             300.402319 &            False \\
38 &   300.466459 &  False &             300.404677 &            False \\
39 &    300.47186 &  False &             300.414776 &            False \\
40 &   300.549044 &  False &              300.56892 &            False \\
\bottomrule
\end{tabular}

C:\Users\Volpe\AppData\Local\Temp/ipykernel_17912/2677878528.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(joined_table.to_latex())

## SAT

In [3]:
txtfile = '../SAT/out/log.txt'
rot_txtfile = '../SAT/out/log-rot.txt'
with open(txtfile, 'r') as f:
    lines = [l.rstrip() for l in f.readlines()]
with open(rot_txtfile, 'r') as f:
    lines_rot = [l.rstrip() for l in f.readlines()]

r1 = re.compile(r".* (Final|optimal) solution .*")
r2 = re.compile(r"Solving problem *")
nonoptimal_reg = re.compile(r"Couldn't")
time_reg = re.compile(r"\d*\b\.\d*\b")

solutions_times = [(float(time_reg.search(l).group(0)), 
                    False if nonoptimal_reg.match(l) else True) 
                   for l in list(filter(r1.match, lines))]
instances = [int(l.split('ins-')[1].split('.txt')[0]) 
             for l in list(filter(r2.match, lines))]

solutions_times_rot = [(float(time_reg.search(l).group(0)), 
                        False if nonoptimal_reg.match(l) else True) 
                        for l in list(filter(r1.match, lines_rot))]
instances_rot = [int(l.split('ins-')[1].split('.txt')[0]) 
                for l in list(filter(r2.match, lines_rot))]

instance_times = {instances[i]: solutions_times[i] for i in range(len(instances))}
instance_times_rot = {instances_rot[i]: solutions_times_rot[i] for i in range(len(instances_rot))}

results = pd.DataFrame(instance_times, index=['Solving Time', 'Solved']).T
results_rot = pd.DataFrame(instance_times_rot, index=['Solving Time', 'Solved']).T
joined_table = results.join(results_rot, rsuffix=' (rotated)').sort_index()

print(joined_table.to_latex())

\begin{tabular}{lllll}
\toprule
{} & Solving Time & Solved & Solving Time (rotated) & Solved (rotated) \\
\midrule
1  &        0.001 &   True &               0.000998 &             True \\
2  &     0.001005 &   True &                  0.003 &             True \\
3  &     0.001001 &   True &                  0.003 &             True \\
4  &        0.005 &   True &                  0.006 &             True \\
5  &     0.006003 &   True &               0.019991 &             True \\
6  &     0.010005 &   True &               0.094997 &             True \\
7  &     0.008997 &   True &               0.171993 &             True \\
8  &     0.011999 &   True &                0.02699 &             True \\
9  &     0.025002 &   True &               0.177991 &             True \\
10 &     0.015002 &   True &               1.527996 &             True \\
11 &     0.526994 &   True &              15.465997 &             True \\
12 &     0.147004 &   True &              10.307425 &             True \\
13 &        0.036 &   True &               7.526007 &             True \\
14 &     0.200004 &   True &              13.441997 &             True \\
15 &     0.044002 &   True &              26.935004 &             True \\
16 &        2.577 &   True &             300.745704 &            False \\
17 &     0.077002 &   True &              60.443352 &             True \\
18 &     0.400993 &   True &             398.218592 &            False \\
19 &     2.365996 &   True &             313.846539 &            False \\
20 &     1.112994 &   True &             308.838917 &            False \\
21 &    12.019999 &   True &             307.573671 &            False \\
22 &    83.508985 &   True &             381.491981 &            False \\
23 &     6.980997 &   True &             218.606984 &             True \\
24 &     1.282004 &   True &              90.249996 &             True \\
25 &    30.123996 &   True &              412.07096 &            False \\
26 &        8.323 &   True &             313.465345 &            False \\
27 &     2.245996 &   True &             303.639596 &            False \\
28 &    12.357997 &   True &             327.107995 &            False \\
29 &     3.068996 &   True &             586.884791 &            False \\
30 &   306.651036 &  False &             430.034332 &            False \\
31 &     0.726995 &   True &               4.689826 &             True \\
32 &   347.863419 &  False &             311.823009 &            False \\
33 &     4.249995 &   True &             101.827429 &             True \\
34 &     8.593995 &   True &             330.611375 &            False \\
35 &    22.312999 &   True &             311.000464 &            False \\
36 &     3.814996 &   True &              64.042751 &             True \\
37 &   390.692096 &  False &             370.993186 &            False \\
38 &   323.595178 &  False &             454.986726 &            False \\
39 &    51.760747 &   True &             331.215381 &            False \\
40 &   400.971704 &  False &             422.434928 &            False \\
\bottomrule
\end{tabular}

C:\Users\Volpe\AppData\Local\Temp/ipykernel_13616/4273354854.py:32: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(joined_table.to_latex())

In [8]:
txtfile = '../SMT/out/log.txt'
with open(txtfile, 'r') as f:
    lines = [l.rstrip() for l in f.readlines()]

r1 = re.compile(r".* (Final|optimal) solution .*")
r2 = re.compile(r"Solving problem *")
nonoptimal_reg = re.compile(r"Couldn't")
time_reg = re.compile(r"\d*\b\.\d*\b")

def replace_with_geq300(time):
    if float(time) >= 300:
        return "geq 300"
    else:
        return time

solutions_times = [(float(time_reg.search(l).group(0)), 
                    False if nonoptimal_reg.match(l) else True) 
                   for l in list(filter(r1.match, lines))]
instances = [int(l.split('ins-')[1].split('.txt')[0]) 
             for l in list(filter(r2.match, lines))]

instance_times = {instances[i]: solutions_times[i] for i in range(len(instances))}

results = pd.DataFrame(instance_times, index=['Solving Time', 'Solved']).T.sort_index()
results['Solving Time'] = results['Solving Time'].apply(replace_with_geq300)

print(results.to_latex())

\begin{tabular}{lll}
\toprule
{} & Solving Time & Solved \\
\midrule
1  &     0.008001 &   True \\
2  &     0.046875 &   True \\
3  &     0.031245 &   True \\
4  &     0.098004 &   True \\
5  &     0.203128 &   True \\
6  &      0.42188 &   True \\
7  &      0.45312 &   True \\
8  &     0.671875 &   True \\
9  &     0.929345 &   True \\
10 &      1.52992 &   True \\
11 &    11.960891 &   True \\
12 &     5.130927 &   True \\
13 &     5.697763 &   True \\
14 &      7.81603 &   True \\
15 &     9.163337 &   True \\
16 &    31.261917 &   True \\
17 &    30.989463 &   True \\
18 &    25.895461 &   True \\
19 &      geq 300 &  False \\
20 &   138.755315 &   True \\
21 &   124.076259 &   True \\
22 &      geq 300 &  False \\
23 &    91.469639 &   True \\
24 &    39.239451 &   True \\
25 &      geq 300 &  False \\
26 &   201.861287 &   True \\
27 &   117.752949 &   True \\
28 &   262.148002 &   True \\
29 &      geq 300 &  False \\
30 &      geq 300 &  False \\
31 &     28.45329 &   True \\
32 &      geq 300 &  False \\
33 &    51.063296 &   True \\
34 &      geq 300 &  False \\
35 &      geq 300 &  False \\
36 &      geq 300 &  False \\
37 &      geq 300 &  False \\
38 &      geq 300 &  False \\
39 &      geq 300 &  False \\
40 &      geq 300 &  False \\
\bottomrule
\end{tabular}

C:\Users\Volpe\AppData\Local\Temp/ipykernel_20892/3217082793.py:27: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(results.to_latex())